server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: RemoveRequestHeader
          args:
            name: Cookie
      routes:
        - id: catalogo
          uri: lb://catalogo-service
          predicates:
            - Path=/api/v1/productos/**
          filters:
            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
