server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: catalogo-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/catalogodb}
    username: ${SPRING_DATASOURCE_USERNAME:catalogouser}
    password: ${SPRING_DATASOURCE_PASSWORD:catalogopass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info

